### ISSUE TITLE
Provide more details about using the Faucet example

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/js-chain-libs#24]
**Describe the bug**
It is not clear when and how to use the `Faucet endpoint example`. How to start a node/testnet, how to invoke the faucet script/example.

**To Reproduce**

**Expected behavior**
The scenario I am thinking about is something like:
1. start jormungandr node
2. create Account address
3. invoke Faucet script in order to send funds from Faucet to the Account address

I am expecting that the Faucet example to provide the entire above (usage) story.

**Additional context**

**Comment by dorin100** [comment]
Ok. I managed to have this working with the below scenario:

1. start jormungandr node 
2. create the `.env` file inside the `\js-chain-libs\examples\faucet` folder
3. update the values of `SECRET_KEY` and `JORMUNGANDR_API` parameters based on the ones generated at step no 1
4. start faucet script - go to `\js-chain-libs\examples\faucet` and run `npm run server`
```D:\iohk\otherProjects\js-chain-libs\examples\faucet>npm run server

> faucet@1.0.0 server D:\iohk\otherProjects\js-chain-libs\examples\faucet
> node server.js

{"level":30,"time":1565774301539,"pid":12156,"hostname":"lenovo","msg":"Server listening at http://127.0.0.1:8300","v":1}
{"level":30,"time":1565774301540,"pid":12156,"hostname":"lenovo","msg":"server listening on 8300","v":1}
```
5. create a new Account address 
6. use the Post endpoint in order to send money to the new Account address using the `faucet app` - ```C:\Users\Dorin>curl -X POST http://localhost:8300/send-money/ca1s5zg6z838arxf922v2yerjx6g753zczcqpc2qv8lcwhe44mj9enty488f70
01dc702519737890fafcd5c83375619e5e3c5868b6be9d58695456a4feb34099```
```
{"level":30,"time":1565774307605,"pid":12156,"hostname":"lenovo","reqId":1,"req":{"method":"POST","url":"/send-money/ca1s5zg6z838arxf922v2yerjx6g753zczcqpc2qv8lcwhe44mj9enty4
88f70","hostname":"localhost:8300","remoteAddress":"127.0.0.1","remotePort":52685},"msg":"incoming request","v":1}
{"level":30,"time":1565774307636,"pid":12156,"hostname":"lenovo","reqId":1,"res":{"statusCode":200},"responseTime":29.227100998163223,"msg":"request completed","v":1}
```
7. verify that the newly created account received the funds
```
$ jcli rest v0 account get ca1s5zg6z838arxf922v2yerjx6g753zczcqpc2qv8lcwhe44mj9enty488f70 --host "http://127.0.0.1:8443/api"
---
counter: 0
delegation: ~
value: 300
```

**Comment by dorin100** [comment]
Hi @elviejo79. Where it would be best for us to create a tutorial for using the Faucet example based on the above steps? Should we use the wiki of this repo? cc: @NicolasDP

**Comment by dorin100** [comment]
@enzoc4 - what does `01dc702519737890fafcd5c83375619e5e3c5868b6be9d58695456a4feb34099` mean? (from the response of the POST call).

**Comment by enzoc4** [comment]
@dorin100 well, it is the hash of the transaction. I added that thinking in querying for that transaction to the node, but now I think it's useless. I think it would be better to just return success or something like that.

**Comment by dorin100** [comment]
@enzoc4 - it is ok as it is. basically, in the future, we should be able to get the transaction details based on the transaction hash.
