### ISSUE TITLE
Unclear results for the `Create transaction` example from Readme

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/js-chain-libs#25]
**Describe the bug**
No expected results/example into the Readme regarding the `Create transaction` example. 
	
**To Reproduce**
1. create a new folder named `make-transaction`
2. copy the pkg/js-chain-libs-0.1.0.tgz to the above created directory
3. in the above folder create the 3 files as explained [here](https://github.com/input-output-hk/js-chain-libs) - `package.json`, `webpack.config.js`, `index.js`
4. run `npm install` and `npm install js-chain-libs-0.1.0.tgz`
5. run `npm run serve` and open a browser in `http://localhost:8080/`

     **Edge browser** console results:
- nothing related to transaction + 1 error
![image](https://user-images.githubusercontent.com/29144964/62928012-5d685580-bdc0-11e9-8a40-0178fa4ec4a5.png)

     **Firefox browser** console results:
- there is a string (hash ?) in the console but I am not sure if that is the expected result. If yes, I suggest adding an expected result also in the Readme.
- If this is the expected result, it would be nice to also know how to do reverse engineering, in order to see if the transaction really has the expected values. 
![image (1)](https://user-images.githubusercontent.com/29144964/62928134-9d2f3d00-bdc0-11e9-8c64-6b4497ed4cd3.png)

**Expected behavior**
It should be clear what browser to use, how the result should look, how to interpret it and how to use it forward.

**Additional context**

**Comment by NicolasDP** [comment]
@dorin100 , the changes in #28  and #29 should fix the issues you reported.
